version: "0.5"

processes:
  redis:
    command: redis-server
    availability:
      restart: on_failure
    readiness_probe:
      exec:
        command: redis-cli ping
      initial_delay_seconds: 2
      period_seconds: 2
      timeout_seconds: 2
      success_threshold: 1
      failure_threshold: 5

  gateway:
    command: ./build/roamind-gateway
    depends_on:
      redis:
        condition: process_healthy
    availability:
      restart: on_failure
    readiness_probe:
      exec:
        command: "test -f ./build/roamind-gateway"
      initial_delay_seconds: 1
      period_seconds: 5
      timeout_seconds: 2
      success_threshold: 1
      failure_threshold: 5
    env_file: .env

  agent:
    command: bash -c "cd agent && conda run --no-capture-output -n base python -m app.main"
    depends_on:
      redis:
        condition: process_healthy
    availability:
      restart: on_failure
    readiness_probe:
      exec:
        command: redis-cli ping
      initial_delay_seconds: 2
      period_seconds: 5
      timeout_seconds: 2
      success_threshold: 1
      failure_threshold: 5
    env_file: .env

  # actuator:
  #   command: ./build/roamind-actuator
  #   depends_on:
  #     redis:
  #       condition: process_healthy
  #   availability:
  #     restart: on_failure
  #   env_file: .env
